### ISSUE TITLE
cant download model and json

### ISSUE THREAD

**Issue by alanzhai219** [PaddlePaddle/PaddleNLP#3099]
for branch release/2.1

https://github.com/PaddlePaddle/PaddleNLP/blob/0e1f3682f8038b0f93b15565acb4b2edbb5d9a1e/paddlenlp/transformers/ernie_gen/modeling.py#L268

some link has gone. 

could anyone fix it?

Thanks.

**Comment by azhai219** [comment]
anyone can help?
checkout to release/2.1.0
```bash
cd //PaddleNLP/examples/language_model/bert
python export_model.py --model_type ernie --model_path ernie-gen-base-en  --output_path test/ernie-gen-base-en
python export_model.py --model_type ernie --model_path ernie-gen-large-en --output_path test/ernie-gen-large-en
python export_model.py --model_type ernie --model_path ernie-gen-large-430g-en  --output_path test/ernie-gen-large-430g-en
```
can't reach the network with the code 404!

**Comment by LemonNoel** [comment]
> anyone can help? checkout to release/2.1.0
> 
> ```shell
> cd //PaddleNLP/examples/language_model/bert
> python export_model.py --model_type ernie --model_path ernie-gen-base-en  --output_path test/ernie-gen-base-en
> python export_model.py --model_type ernie --model_path ernie-gen-large-en --output_path test/ernie-gen-large-en
> python export_model.py --model_type ernie --model_path ernie-gen-large-430g-en  --output_path test/ernie-gen-large-430g-en
> ```
> 
> can't reach the network with the code 404!

The example in `/PaddleNLP/examples/language_model/bert` is a sequence classification task. But `ernie-gen` supports text generation task only. Besides, the model structure of `ernie-gen` is different from that of `ernie`. You can refer to [this table](https://paddlenlp.readthedocs.io/zh/latest/model_zoo/index.html#id2) for more information.

**Comment by LemonNoel** [comment]
> for branch release/2.1
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/0e1f3682f8038b0f93b15565acb4b2edbb5d9a1e/paddlenlp/transformers/ernie_gen/modeling.py#L268
> 
> some link has gone.
> 
> could anyone fix it?
> 
> Thanks.

Can you provide more information about how to reproduce it?

**Comment by azhai219** [comment]
> > for branch release/2.1
> > https://github.com/PaddlePaddle/PaddleNLP/blob/0e1f3682f8038b0f93b15565acb4b2edbb5d9a1e/paddlenlp/transformers/ernie_gen/modeling.py#L268
> > 
> > some link has gone.
> > could anyone fix it?
> > Thanks.
> 
> Can you provide more information about how to reproduce it?

You can just wget such link to reproduce it. 
For example, `wget https://paddlenlp.bj.bcebos.com/models/transformers/community/ernie-gen-large-en-430g/model_state.pdparams` failed to access.

Thanks.

**Comment by azhai219** [comment]
> 

Actually, I just follow the readme to export the *.pdmodel while can't access the link. Could you help check it. Thanks.

**Comment by LemonNoel** [comment]
If you ran the following command and got a `RuntimeError` , it's expected because `ernie-gen-base-en` **CAN NOT BE LOADED** by `ErnieForSequenceClassification`.

> ```shell
> python export_model.py --model_type ernie --model_path ernie-gen-base-en  --output_path test/ernie-gen-base-en
> ```

The link provided is missing because `ernie-gen-base-en` is not in the default list of ernie and it turns to **community** channel. 
`https://paddlenlp.bj.bcebos.com/models/transformers/community/ernie-gen-large-en-430g/model_state.pdparams` 
While the link in [model.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie_gen/modeling.py#L277) is 
`https://bj.bcebos.com/paddlenlp/models/transformers/ernie-gen-large/ernie_gen_large.pdparams`.


If you want to try other ernie models, please refer to [this model list](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/modeling.py#L665-L739).

**Comment by azhai219** [comment]
> 


Sounds reasonable. But below links still failed. So, @LemonNoel could you help fix it? Thanks
```
https://bj.bcebos.com/paddlenlp/models/community/ernie-doc-base-zh/model_config.json
https://bj.bcebos.com/paddlenlp/models/community/ernie-doc-base-en/model_config.json
https://bj.bcebos.com/paddlenlp/models/community/ernie-gen-base-en/model_config.json
https://bj.bcebos.com/paddlenlp/models/community/ernie-gen-large-en/model_config.json
https://bj.bcebos.com/paddlenlp/models/community/ernie-gen-large-en-430g/model_config.json
https://bj.bcebos.com/paddlenlp/models/community/ernie-gram-zh/model_config.json
```

**Comment by LemonNoel** [comment]
Can I know which example you ran? And what do you aim to do?

**Comment by LemonNoel** [comment]
If the code file is `/PaddleNLP/examples/language_model/bert/export_model.py` without adaption, I don't think it is a bug. Code 404 means that you **should not** load `ernie-gen`, `ernie-doc` or `ernie-gram` by `ErnieForSequenceClassification`. 

If you want to export these model as a static graph, you need to modify the `ErnieForSequenceClassification` class at [#L56](https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.1/examples/language_model/bert/run_glue.py#L56) as `ErnieDocForSequenceClassification` for `ernie-doc-base-xx`, as `ErnieGramForSequenceClassification` for `ernie-gram-xx`, as `ErnieForGeneration` for `ernie-gen-xx`. 

For the model parameters, you can directly download them using the [links](https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.1/paddlenlp/transformers/ernie_gen/modeling.py#L270-L275).

For the config files, if they are not given, the model will use these [configs](https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.1/paddlenlp/transformers/ernie_gen/modeling.py#L224-L266) by default. You can copy them to a new file `model_config.json` and move it to the directory of model parameters.

**Comment by azhai219** [comment]
> Can I know which example you ran? And what do you aim to do?

- I just want to export the **static models of bert and ernie** in different branches in order to support inference engine. Actually, it is not easy for your repo changes so quickly.

- It seems that model name shows in the py code instead of the readme.
It is much appreciated if you can provide me such the bert and ernie model list and convert tutorial. If possilble, please teach me how to export ernie.

- I really understand the different branch support the different model. It may be helpful and clear to show the model list in the readme.
 
Thanks.
