### ISSUE TITLE
[Question]:  Regarding the funsd data set preparation script for custom training

### ISSUE THREAD

**Issue by chinnaGuggilla** [PaddlePaddle/PaddleNLP#4531]
### 请提出你的问题

Hi @authors,
Could you add the FUNSD training set preparation script for ernie-layout custom training. 
This data set - "[https://bj.bcebos.com/paddlenlp/datasets/funsd.tar.gz"](https://bj.bcebos.com/paddlenlp/datasets/funsd.tar.gz%22)  is preformatted and could you add the conversion script/data prepartion script for the same.
Thanks,

**Comment by linjieccc** [comment]
@chinnaGuggilla Hi,  Thanks for your interest on ERNIE-Layout!

You can just follow our data format directly, the data format is universal for all the NER tasks. The conversion scripts will not be open-sourced as it only works on FUNSD

**Comment by nehashinde-canopy** [comment]
I want to load a custom dataset to train earnie-layout on. Instead of using load_dataset from "datasets" library, how can I load files from my custom dataset folder and split it into train test val? My custom dataset would have same format as funsd dataset so that it will have image files and annotation files.
