### ISSUE TITLE
[Question]: How to represent paginated documents as a single instance of training data for whole document?

### ISSUE THREAD

**Issue by rr191211** [PaddlePaddle/PaddleNLP#4662]
### 请提出你的问题

How to handle multiple page document with Ernie-layout models ? Do I need to train the model on each page from multiple page documents and use it for multi page inference?  or combine all the pages into one vertically stretched image and then run the pipeline considering it as one page?   The docPrompt model seems to be the best suited for multiple pages document, do you mind sharing the finetuning strategy about docPrompt model(Taskflow("document_intelligence"))? Thx.

**Comment by linjieccc** [comment]
@rr191211 Hi, I would suggest to do inference for each page separately especially when there are a lot of pages. The finetuning strategy of DocPrompt is not open-sourced at present due to commercial consideration. I hope that [the applications of document information extraction](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/document/README_en.md) may be an alternative solution and helps in your scene.
