### ISSUE TITLE
[Question]: Checkpoints for ernie-layout fine-tuning

### ISSUE THREAD

**Issue by kaysinb** [PaddlePaddle/PaddleNLP#6185]
### 请提出你的问题

In[ ernie-layout  page](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout), you suggest using out-of-box model for VQA task:
`docprompt = Taskflow("document_intelligence", lang="en")`
But for fine-tuning, you provide checkpoints "ernie-layoutx-base-uncased" which initially works much worse than the  "out-of-box model".  Could you please provide checkpoints of the "out-of-box model"?

**Comment by linjieccc** [comment]
@kaysinb Thank you for your interest in Ernie-Layout. DocPrompt is trained on a large scale VQA & information extraction data based on Ernie-Layout. Due to commercial considerations, we currently do not plan to open-source the fine-tuning process. Alternatively, you can consider using UIE-X for fine-tuning.
